from providers.imagebam import get_real_imagebam_url
from providers.pixhost import get_real_pixhost_url
from providers.postimg import get_real_postimg_url
from providers.imgbox import get_real_imgbox_url
from providers.turboimagehost import get_real_turboimagehost_url